"""
Data Sender Module (DSM) for OCM

This module is responsible for the actual transmission of the final output using NMM
for underlying network communication. It sends data to the web server based on the
type of output:
- JSON objects for simple API responses (from RCMIM)
- HTML and/or PDF files for reports (generated by HRPM/PRFPM)
- Handles proper formatting, encoding, and delivery confirmation
"""

import asyncio
import logging
import json
import base64
import mimetypes
from typing import Dict, Any, Optional, List, Union
from datetime import datetime, timedelta
from dataclasses import dataclass, asdict
from enum import Enum
from pathlib import Path
import hashlib
import gzip
import io

class DataType(Enum):
    """Types of data being sent."""
    JSON = "json"
    HTML = "html" 
    PDF = "pdf"
    BINARY = "binary"
    TEXT = "text"

class CompressionType(Enum):
    """Compression types for data transmission."""
    NONE = "none"
    GZIP = "gzip"
    DEFLATE = "deflate"

@dataclass
class DataPacket:
    """Information about a data packet being sent."""
    request_id: str
    data_type: DataType
    content: Union[str, bytes]
    content_size: int
    content_hash: str
    compression: CompressionType
    compressed_size: Optional[int] = None
    metadata: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}

class DataSenderModule:
    """
    Data Sender Module (DSM)
    
    Handles the actual transmission of final output:
    - Formats and encodes different data types
    - Applies compression when appropriate
    - Coordinates with NMM for network transmission
    - Manages delivery confirmations and retries
    - Provides transmission statistics and monitoring
    """
    
    def __init__(self, config: Dict[str, Any]):
        """Initialize the DSM module."""
        self.logger = logging.getLogger(__name__)
        self.module_name = "DSM"
        self.is_active = False
        
        # Configuration
        self.config = config
        self.network_config = config.get('network', {})
        
        # Compression settings
        self.compression_enabled = True
        self.compression_threshold = 1024  # Compress data > 1KB
        self.default_compression = CompressionType.GZIP
        
        # Module references
        self.nmm = None  # Network Management Module reference
        
        # Statistics
        self.stats = {
            'data_packets_sent': 0,
            'json_responses_sent': 0,
            'html_reports_sent': 0,
            'pdf_reports_sent': 0,
            'bytes_sent_raw': 0,
            'bytes_sent_compressed': 0,
            'compression_ratio': 1.0,
            'transmission_failures': 0,
            'retry_attempts': 0,
            'average_send_time': 0.0
        }
        
        # Transmission tracking
        self.transmission_history = {}  # request_id -> transmission_info
        self.max_history = 1000
        
        self.logger.info(f"{self.module_name} initialized - compression: {self.compression_enabled}")
    
    def set_module_references(self, modules: Dict[str, Any]):
        """Set references to other modules."""
        self.nmm = modules.get('NMM')
        if not self.nmm:
            self.logger.warning("NMM reference not found - network transmission may not work")
    
    async def start(self):
        """Start the DSM module."""
        try:
            self.is_active = True
            
            # Start statistics updater
            asyncio.create_task(self._update_statistics())
            
            # Start transmission history cleaner
            asyncio.create_task(self._history_cleaner())
            
            self.logger.info("DSM started successfully - data transmission ready")
            
        except Exception as e:
            self.logger.error(f"Failed to start DSM: {e}")
            raise
    
    async def stop(self):
        """Stop the DSM module gracefully."""
        try:
            self.is_active = False
            self.logger.info("DSM stopped successfully")
            
        except Exception as e:
            self.logger.error(f"Error stopping DSM: {e}")
    
    async def health_check(self) -> Dict[str, Any]:
        """Perform health check."""
        try:
            nmm_health = await self.nmm.health_check() if self.nmm else {'healthy': False}
            is_healthy = (
                self.is_active and 
                self.nmm is not None and
                nmm_health.get('healthy', False)
            )
            
            return {
                'healthy': is_healthy,
                'is_active': self.is_active,
                'nmm_available': self.nmm is not None,
                'nmm_healthy': nmm_health.get('healthy', False),
                'module': 'dsm'
            }
        except Exception as e:
            return {
                'healthy': False,
                'error': str(e),
                'module': 'dsm'
            }
    
    async def send_data(self, request_info) -> Dict[str, Any]:
        """Send data based on request information."""
        try:
            start_time = datetime.now()
            
            # Determine data type and prepare packet
            data_packet = await self._prepare_data_packet(request_info)
            
            # Send the data packet
            result = await self._transmit_data_packet(data_packet, request_info)
            
            # Calculate transmission time
            end_time = datetime.now()
            transmission_time = (end_time - start_time).total_seconds()
            
            # Update statistics
            await self._update_transmission_stats(data_packet, transmission_time, result)
            
            # Store transmission history
            self.transmission_history[request_info.request_id] = {
                'timestamp': start_time.isoformat(),
                'data_type': data_packet.data_type.value,
                'content_size': data_packet.content_size,
                'compressed_size': data_packet.compressed_size,
                'transmission_time': transmission_time,
                'success': result.get('success', False),
                'destination': request_info.destination
            }
            
            # Maintain history size limit
            if len(self.transmission_history) > self.max_history:
                oldest_key = min(self.transmission_history.keys())
                del self.transmission_history[oldest_key]
            
            return result
            
        except Exception as e:
            self.logger.error(f"Error sending data for request {request_info.request_id}: {e}")
            self.stats['transmission_failures'] += 1
            
            return {
                'success': False,
                'error': str(e),
                'request_id': request_info.request_id
            }
    
    async def _prepare_data_packet(self, request_info) -> DataPacket:
        """Prepare data packet based on request type."""
        try:
            metadata = request_info.metadata or {}
            
            if request_info.request_type.value == 'api_response':
                return await self._prepare_json_packet(request_info)
                
            elif request_info.request_type.value == 'td_report':
                return await self._prepare_report_packet(request_info)
                
            elif request_info.request_type.value == 'system_notification':
                return await self._prepare_notification_packet(request_info)
                
            else:
                raise ValueError(f"Unknown request type: {request_info.request_type}")
                
        except Exception as e:
            self.logger.error(f"Error preparing data packet: {e}")
            raise
    
    async def _prepare_json_packet(self, request_info) -> DataPacket:
        """Prepare JSON data packet for API responses."""
        try:
            # Get JSON content from metadata
            json_data = request_info.metadata.get('response_data', {})
            
            # Add standard response fields
            response = {
                'request_id': request_info.request_id,
                'timestamp': datetime.now().isoformat(),
                'status': 'success',
                'data': json_data
            }
            
            # Convert to JSON string
            content = json.dumps(response, ensure_ascii=False, indent=2)
            content_bytes = content.encode('utf-8')
            
            # Apply compression if needed
            compressed_content, compression_type, compressed_size = await self._apply_compression(content_bytes)
            
            return DataPacket(
                request_id=request_info.request_id,
                data_type=DataType.JSON,
                content=compressed_content,
                content_size=len(content_bytes),
                content_hash=hashlib.sha256(content_bytes).hexdigest(),
                compression=compression_type,
                compressed_size=compressed_size,
                metadata={
                    'original_encoding': 'utf-8',
                    'mime_type': 'application/json'
                }
            )
            
        except Exception as e:
            self.logger.error(f"Error preparing JSON packet: {e}")
            raise
    
    async def _prepare_report_packet(self, request_info) -> DataPacket:
        """Prepare report data packet (HTML/PDF)."""
        try:
            metadata = request_info.metadata
            report_format = request_info.report_format or ['HTML']
            
            # Prepare multi-part report if both HTML and PDF are requested
            if len(report_format) > 1:
                return await self._prepare_multipart_report(request_info)
            
            # Single format report
            format_type = report_format[0].upper()
            
            if format_type == 'HTML':
                html_content = metadata.get('html_content', '')
                if not html_content:
                    raise ValueError("HTML content not found in metadata")
                
                content_bytes = html_content.encode('utf-8')
                data_type = DataType.HTML
                mime_type = 'text/html'
                
            elif format_type == 'PDF':
                pdf_content = metadata.get('pdf_content', b'')
                if not pdf_content:
                    raise ValueError("PDF content not found in metadata")
                
                content_bytes = pdf_content if isinstance(pdf_content, bytes) else pdf_content.encode()
                data_type = DataType.PDF
                mime_type = 'application/pdf'
                
            else:
                raise ValueError(f"Unsupported report format: {format_type}")
            
            # Apply compression
            compressed_content, compression_type, compressed_size = await self._apply_compression(content_bytes)
            
            return DataPacket(
                request_id=request_info.request_id,
                data_type=data_type,
                content=compressed_content,
                content_size=len(content_bytes),
                content_hash=hashlib.sha256(content_bytes).hexdigest(),
                compression=compression_type,
                compressed_size=compressed_size,
                metadata={
                    'mime_type': mime_type,
                    'report_format': format_type,
                    'template_used': request_info.template_used
                }
            )
            
        except Exception as e:
            self.logger.error(f"Error preparing report packet: {e}")
            raise
    
    async def _prepare_multipart_report(self, request_info) -> DataPacket:
        """Prepare multipart report with both HTML and PDF."""
        try:
            metadata = request_info.metadata
            
            # Create multipart content
            multipart_data = {
                'request_id': request_info.request_id,
                'timestamp': datetime.now().isoformat(),
                'report_type': 'multipart',
                'parts': []
            }
            
            # Add HTML part if available
            html_content = metadata.get('html_content')
            if html_content:
                multipart_data['parts'].append({
                    'type': 'html',
                    'mime_type': 'text/html',
                    'content': base64.b64encode(html_content.encode('utf-8')).decode('ascii'),
                    'encoding': 'base64'
                })
            
            # Add PDF part if available  
            pdf_content = metadata.get('pdf_content')
            if pdf_content:
                pdf_bytes = pdf_content if isinstance(pdf_content, bytes) else pdf_content.encode()
                multipart_data['parts'].append({
                    'type': 'pdf',
                    'mime_type': 'application/pdf',
                    'content': base64.b64encode(pdf_bytes).decode('ascii'),
                    'encoding': 'base64'
                })
            
            # Convert to JSON
            content = json.dumps(multipart_data, ensure_ascii=False, indent=2)
            content_bytes = content.encode('utf-8')
            
            # Apply compression
            compressed_content, compression_type, compressed_size = await self._apply_compression(content_bytes)
            
            return DataPacket(
                request_id=request_info.request_id,
                data_type=DataType.JSON,  # Multipart is sent as JSON
                content=compressed_content,
                content_size=len(content_bytes),
                content_hash=hashlib.sha256(content_bytes).hexdigest(),
                compression=compression_type,
                compressed_size=compressed_size,
                metadata={
                    'mime_type': 'application/json',
                    'content_type': 'multipart_report',
                    'parts_count': len(multipart_data['parts'])
                }
            )
            
        except Exception as e:
            self.logger.error(f"Error preparing multipart report: {e}")
            raise
    
    async def _prepare_notification_packet(self, request_info) -> DataPacket:
        """Prepare notification data packet."""
        try:
            # Simple notification structure
            notification = {
                'request_id': request_info.request_id,
                'timestamp': datetime.now().isoformat(),
                'type': 'system_notification',
                'message': request_info.metadata.get('message', ''),
                'priority': request_info.priority.value
            }
            
            content = json.dumps(notification, ensure_ascii=False)
            content_bytes = content.encode('utf-8')
            
            # Apply compression
            compressed_content, compression_type, compressed_size = await self._apply_compression(content_bytes)
            
            return DataPacket(
                request_id=request_info.request_id,
                data_type=DataType.JSON,
                content=compressed_content,
                content_size=len(content_bytes),
                content_hash=hashlib.sha256(content_bytes).hexdigest(),
                compression=compression_type,
                compressed_size=compressed_size,
                metadata={
                    'mime_type': 'application/json',
                    'notification_type': 'system'
                }
            )
            
        except Exception as e:
            self.logger.error(f"Error preparing notification packet: {e}")
            raise
    
    async def _apply_compression(self, content: bytes) -> tuple[bytes, CompressionType, Optional[int]]:
        """Apply compression to content if beneficial."""
        try:
            if not self.compression_enabled or len(content) < self.compression_threshold:
                return content, CompressionType.NONE, None
            
            if self.default_compression == CompressionType.GZIP:
                # Apply GZIP compression
                buffer = io.BytesIO()
                with gzip.GzipFile(fileobj=buffer, mode='wb') as f:
                    f.write(content)
                
                compressed = buffer.getvalue()
                
                # Only use compression if it reduces size significantly (>10%)
                compression_ratio = len(compressed) / len(content)
                if compression_ratio < 0.9:
                    return compressed, CompressionType.GZIP, len(compressed)
            
            # Return uncompressed if compression doesn't help
            return content, CompressionType.NONE, None
            
        except Exception as e:
            self.logger.error(f"Error applying compression: {e}")
            return content, CompressionType.NONE, None
    
    async def _transmit_data_packet(self, data_packet: DataPacket, request_info) -> Dict[str, Any]:
        """Transmit data packet using NMM."""
        try:
            if not self.nmm:
                raise ValueError("NMM not available for data transmission")
            
            # Prepare transmission data
            transmission_data = {
                'request_id': data_packet.request_id,
                'content_type': data_packet.data_type.value,
                'compression': data_packet.compression.value,
                'content_size': data_packet.content_size,
                'compressed_size': data_packet.compressed_size,
                'content_hash': data_packet.content_hash,
                'metadata': data_packet.metadata
            }
            
            # Add content based on data type
            if isinstance(data_packet.content, bytes):
                transmission_data['content'] = base64.b64encode(data_packet.content).decode('ascii')
                transmission_data['content_encoding'] = 'base64'
            else:
                transmission_data['content'] = data_packet.content
                transmission_data['content_encoding'] = 'utf-8'
            
            # Send via NMM
            result = await self.nmm.send_data(
                destination=request_info.destination,
                data=transmission_data,
                request_id=data_packet.request_id
            )
            
            # Update statistics based on data type
            if data_packet.data_type == DataType.JSON:
                if data_packet.metadata.get('content_type') == 'multipart_report':
                    self.stats['html_reports_sent'] += 1
                    self.stats['pdf_reports_sent'] += 1
                else:
                    self.stats['json_responses_sent'] += 1
            elif data_packet.data_type == DataType.HTML:
                self.stats['html_reports_sent'] += 1
            elif data_packet.data_type == DataType.PDF:
                self.stats['pdf_reports_sent'] += 1
            
            self.stats['data_packets_sent'] += 1
            
            return result
            
        except Exception as e:
            self.logger.error(f"Error transmitting data packet: {e}")
            raise
    
    async def _update_transmission_stats(self, data_packet: DataPacket, transmission_time: float, result: Dict[str, Any]):
        """Update transmission statistics."""
        try:
            # Update byte counters
            self.stats['bytes_sent_raw'] += data_packet.content_size
            
            if data_packet.compressed_size:
                self.stats['bytes_sent_compressed'] += data_packet.compressed_size
                # Update compression ratio
                total_raw = self.stats['bytes_sent_raw']
                total_compressed = self.stats['bytes_sent_compressed']
                if total_raw > 0:
                    self.stats['compression_ratio'] = total_compressed / total_raw
            
            # Update transmission time average
            current_avg = self.stats['average_send_time']
            packets_sent = self.stats['data_packets_sent']
            
            if packets_sent > 0:
                self.stats['average_send_time'] = (current_avg * packets_sent + transmission_time) / (packets_sent + 1)
            else:
                self.stats['average_send_time'] = transmission_time
            
        except Exception as e:
            self.logger.error(f"Error updating transmission stats: {e}")
    
    async def _update_statistics(self):
        """Periodically update statistics."""
        while self.is_active:
            try:
                # Additional statistics calculations can be added here
                await asyncio.sleep(30)
                
            except Exception as e:
                self.logger.error(f"Error in statistics updater: {e}")
                await asyncio.sleep(30)
    
    async def _history_cleaner(self):
        """Clean up old transmission history."""
        while self.is_active:
            try:
                current_time = datetime.now()
                cutoff_time = current_time - timedelta(hours=24)  # Keep 24 hours of history
                
                # Remove old entries
                old_entries = []
                for request_id, info in self.transmission_history.items():
                    try:
                        entry_time = datetime.fromisoformat(info['timestamp'])
                        if entry_time < cutoff_time:
                            old_entries.append(request_id)
                    except:
                        old_entries.append(request_id)  # Remove invalid entries
                
                for request_id in old_entries:
                    del self.transmission_history[request_id]
                
                if old_entries:
                    self.logger.info(f"Cleaned up {len(old_entries)} old transmission history entries")
                
                await asyncio.sleep(3600)  # Clean every hour
                
            except Exception as e:
                self.logger.error(f"Error in history cleaner: {e}")
                await asyncio.sleep(3600)
    
    async def update_ssl_certificates(self, cert_data: Dict[str, Any]):
        """Update SSL certificates (forward to NMM)."""
        try:
            if self.nmm:
                await self.nmm.update_ssl_certificates(cert_data)
                self.logger.info("SSL certificate update forwarded to NMM")
            else:
                self.logger.warning("NMM not available for SSL certificate update")
                
        except Exception as e:
            self.logger.error(f"Error updating SSL certificates: {e}")
    
    def get_transmission_history(self, request_id: Optional[str] = None) -> Dict[str, Any]:
        """Get transmission history."""
        if request_id:
            return self.transmission_history.get(request_id, {})
        
        return self.transmission_history.copy()
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get detailed transmission statistics."""
        stats = self.stats.copy()
        
        # Add additional computed statistics
        stats['total_data_saved_by_compression'] = max(0, stats['bytes_sent_raw'] - stats['bytes_sent_compressed'])
        stats['compression_efficiency'] = (1.0 - stats['compression_ratio']) * 100 if stats['compression_ratio'] < 1 else 0
        stats['success_rate'] = ((stats['data_packets_sent'] - stats['transmission_failures']) / max(1, stats['data_packets_sent'])) * 100
        
        return stats
    
    def get_status(self) -> Dict[str, Any]:
        """Get current DSM status."""
        return {
            'module': self.module_name,
            'active': self.is_active,
            'compression_enabled': self.compression_enabled,
            'compression_threshold': self.compression_threshold,
            'nmm_available': self.nmm is not None,
            'transmission_history_size': len(self.transmission_history),
            'stats': self.get_statistics()
        } 